server:
  port: 8086

spring:
  application:
    name: driver-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5437/driver_db}
    username: ${DB_USER:driver}
    password: ${DB_PASS:driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

auth:
  server:
    url: ${AUTH_SERVER_URL:http://auth-server:8089}
    jwks-uri: ${AUTH_SERVER_JWKS_URI:http://auth-server:8089/oauth2/jwks}
  client:
    id: ${CLIENT_ID:driver-service}
    secret: ${CLIENT_SECRET:7gc13nP8d87F3MzGZxT5qV8qtjqnkPTpKEQwdhjCkAk=}
