version: '3.8'

services:
  odoo-db:
    image: postgres:15
    container_name: odoo-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - pfe-network

  odoo:
    image: odoo:16
    container_name: odoo-instance
    depends_on:
      - odoo-db
    ports:
      - "8069:8069"
    command: ["odoo", "-c", "/etc/odoo/odoo.conf"]
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
    networks:
      - pfe-network

networks:
  pfe-network:
    external: true

volumes:
  odoo-db-data:
  odoo-data: