-- V1 — Schéma de référence de l'ErpAdapterService.
--
-- Ce service laissait Hibernate créer ses tables (`ddl-auto: update`) sur une base H2 **persistante**
-- contenant les correspondances de champs et les curseurs de synchronisation de chaque client.
-- Trois conséquences :
--
--   1. aucun historique — impossible de dire dans quel état est une base, ni de rejouer sa création ;
--   2. `update` n'enlève et ne renomme jamais rien : une colonne retirée d'une entité reste, et le
--      schéma dérive de son modèle sans que rien ne le signale ;
--   3. rien à examiner en revue : le schéma n'existait nulle part sous forme lisible.
--
-- Ce fichier n'est pas deviné. Il a été extrait du schéma réel, par org.h2.tools.Script sur la base
-- en service, puis remis en forme. Les bases déjà créées sont adoptées via baseline-on-migrate ;
-- une base neuve part de ce script.
--
-- Hibernate passe de `update` à `validate` : il ne modifie plus rien mais refuse de démarrer si ce
-- schéma et les entités divergent. C'est la seule garantie que `update` apportait, gardée sans le
-- pouvoir de réécrire la base en silence.

CREATE TABLE IF NOT EXISTS ERP_FIELD_MAPPING (
    ID              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CANONICAL_FIELD CHARACTER VARYING(64),
    CREATED_AT      TIMESTAMP(6) NOT NULL,
    CUSTOM_KEY      CHARACTER VARYING(64),
    PROVIDER        CHARACTER VARYING(32) NOT NULL,
    READ_AS         CHARACTER VARYING(24) NOT NULL,
    SOURCE_PATH     CHARACTER VARYING(256) NOT NULL,
    TENANT_ID       UUID NOT NULL,
    UPDATED_AT      TIMESTAMP(6),
    UPDATED_BY      CHARACTER VARYING(128),
    CONSTRAINT PK_ERP_FIELD_MAPPING PRIMARY KEY (ID),
    CONSTRAINT UK_ERP_FIELD_MAPPING UNIQUE (TENANT_ID, CANONICAL_FIELD, CUSTOM_KEY)
);

CREATE TABLE IF NOT EXISTS ERP_MAPPING (
    ID           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CAPABILITY   CHARACTER VARYING(64) NOT NULL,
    CREATED_AT   TIMESTAMP(6) NOT NULL,
    MAPPING_TYPE CHARACTER VARYING(16) NOT NULL,
    ODOO_NAME    CHARACTER VARYING(128) NOT NULL,
    TARGET_MODEL CHARACTER VARYING(128) NOT NULL,
    TENANT_ID    UUID NOT NULL,
    CONSTRAINT PK_ERP_MAPPING PRIMARY KEY (ID),
    CONSTRAINT UK_ERP_MAPPING UNIQUE (TENANT_ID, CAPABILITY)
);

CREATE TABLE IF NOT EXISTS ERP_POLL_CURSOR (
    TENANT_ID    UUID NOT NULL,
    CURSOR_VALUE CHARACTER VARYING(64) NOT NULL,
    UPDATED_AT   TIMESTAMP(6),
    CONSTRAINT PK_ERP_POLL_CURSOR PRIMARY KEY (TENANT_ID)
);

CREATE TABLE IF NOT EXISTS IDEMPOTENT_TRANSACTION (
    TRANSACTION_ID   CHARACTER VARYING(255) NOT NULL,
    ERP_ORDER_ID     CHARACTER VARYING(255),
    PROCESSED_AT     TIMESTAMP(6),
    RESPONSE_PAYLOAD CHARACTER VARYING,
    STATUS           CHARACTER VARYING(255),
    TENANT_ID        UUID,
    CONSTRAINT PK_IDEMPOTENT_TRANSACTION PRIMARY KEY (TRANSACTION_ID)
);
