package com.asm.erpadapter.adapter.erpnext;

import com.asm.erpadapter.dto.*;
import com.asm.erpadapter.exception.ErpAdapterException;
import com.asm.erpadapter.port.ErpLookupPort;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static com.asm.erpadapter.adapter.erpnext.ErpNextRestClient.*;

/**
 * ERPNext implementation of {@link ErpLookupPort} (ERPNext v15/16, Frappe REST).
 *
 * <p><b>Import unit = the Sales Order to deliver.</b> Unlike Odoo (which auto-creates an outgoing
 * {@code stock.picking} on confirmation), ERPNext has no pre-created "ready" delivery document — the
 * Delivery Note is created only <em>at shipping time</em> from the Sales Order. So the "ready to
 * deliver" queue is the set of confirmed Sales Orders still awaiting delivery ({@code status} in
 * "To Deliver"/"To Deliver and Bill"). ASM imports the Sales Order; on delivery it creates + submits
 * the Delivery Note (Phase B write-back = the analog of Odoo {@code button_validate}). {@code blNumber}
 * is therefore assigned by ERPNext only when ASM delivers, not at import.
 *
 * <p><b>Company scoping (1 instance = 1 company):</b> an ERPNext instance can host several companies
 * (a bare install already ships a "(Demo)" company). Every read is scoped to a single company resolved
 * by {@link #resolveCompany()}: the configured {@code company} key, else the only company, else a
 * loud error asking the admin to pick one. Never a silent {@code first()}.
 *
 * <p><b>ASM owns what the ERP can't standardize:</b> warehouse GPS (ERPNext warehouses carry no
 * coordinates → ASM geocodes) and the BL PDF (generated by ASM; {@code blNumber} is only the ERP
 * reference for reconciliation).
 */
@Component("erpnextLookup")
@RequiredArgsConstructor
@Slf4j
public class ErpNextLookupAdapter implements ErpLookupPort {

    private final ErpNextRestClient erp;
    private final com.asm.erpadapter.mapping.ErpNextFieldMappingResolver fieldMapping;

    // ── Mapped reads ──────────────────────────────────────────────────────────────────────────────
    // Each canonical value goes through the tenant's mapping first and falls back to the reader that
    // ran before mapping existed, so a tenant who has mapped nothing behaves exactly as before.

    private static final com.asm.erpadapter.mapping.CanonicalField
            ERP_ORDER_ID = com.asm.erpadapter.mapping.CanonicalField.ERP_ORDER_ID,
            BL_NUMBER = com.asm.erpadapter.mapping.CanonicalField.BL_NUMBER,
            SALE_ORDER_REF = com.asm.erpadapter.mapping.CanonicalField.SALE_ORDER_REF,
            CUSTOMER_REF = com.asm.erpadapter.mapping.CanonicalField.CUSTOMER_REF,
            CUSTOMER_NAME = com.asm.erpadapter.mapping.CanonicalField.CUSTOMER_NAME,
            CUSTOMER_PHONE = com.asm.erpadapter.mapping.CanonicalField.CUSTOMER_PHONE,
            DELIVERY_ADDRESS = com.asm.erpadapter.mapping.CanonicalField.DELIVERY_ADDRESS,
            DELIVERY_CITY = com.asm.erpadapter.mapping.CanonicalField.DELIVERY_CITY,
            DELIVERY_POSTAL_CODE = com.asm.erpadapter.mapping.CanonicalField.DELIVERY_POSTAL_CODE,
            DELIVERY_INSTRUCTIONS = com.asm.erpadapter.mapping.CanonicalField.DELIVERY_INSTRUCTIONS,
            TOTAL_AMOUNT = com.asm.erpadapter.mapping.CanonicalField.TOTAL_AMOUNT,
            CURRENCY = com.asm.erpadapter.mapping.CanonicalField.CURRENCY,
            COD_REQUIRED = com.asm.erpadapter.mapping.CanonicalField.COD_REQUIRED,
            COD_AMOUNT = com.asm.erpadapter.mapping.CanonicalField.COD_AMOUNT,
            DATE_ORDER = com.asm.erpadapter.mapping.CanonicalField.DATE_ORDER,
            SCHEDULED_AT = com.asm.erpadapter.mapping.CanonicalField.SCHEDULED_AT,
            PRIORITY = com.asm.erpadapter.mapping.CanonicalField.PRIORITY,
            WAREHOUSE_CODE = com.asm.erpadapter.mapping.CanonicalField.WAREHOUSE_CODE,
            WAREHOUSE_NAME = com.asm.erpadapter.mapping.CanonicalField.WAREHOUSE_NAME,
            READY = com.asm.erpadapter.mapping.CanonicalField.READY,
            ITEM_SKU = com.asm.erpadapter.mapping.CanonicalField.ITEM_SKU,
            ITEM_NAME = com.asm.erpadapter.mapping.CanonicalField.ITEM_NAME,
            ITEM_QUANTITY = com.asm.erpadapter.mapping.CanonicalField.ITEM_QUANTITY,
            ITEM_UNIT_PRICE = com.asm.erpadapter.mapping.CanonicalField.ITEM_UNIT_PRICE,
            ITEM_UNIT_WEIGHT_KG = com.asm.erpadapter.mapping.CanonicalField.ITEM_UNIT_WEIGHT_KG,
            ITEM_PRODUCT_TYPE = com.asm.erpadapter.mapping.CanonicalField.ITEM_PRODUCT_TYPE;

    private String mappedString(com.asm.erpadapter.mapping.CanonicalField field,
                                Map<String, Map<String, Object>> records,
                                java.util.function.Supplier<String> builtIn) {
        Object v = fieldMapping.resolveOrDefault(field, records, builtIn::get);
        return v == null ? null : (v instanceof String s ? s : String.valueOf(v));
    }

    private BigDecimal mappedDecimal(com.asm.erpadapter.mapping.CanonicalField field,
                                     Map<String, Map<String, Object>> records,
                                     java.util.function.Supplier<BigDecimal> builtIn) {
        return asBigDecimal(fieldMapping.resolveOrDefault(field, records, builtIn::get));
    }

    private Integer mappedInt(com.asm.erpadapter.mapping.CanonicalField field,
                              Map<String, Map<String, Object>> records,
                              java.util.function.Supplier<Integer> builtIn) {
        Object v = fieldMapping.resolveOrDefault(field, records, builtIn::get);
        return v instanceof Integer i ? i : asInt(v);
    }

    private LocalDateTime mappedDateTime(com.asm.erpadapter.mapping.CanonicalField field,
                                         Map<String, Map<String, Object>> records,
                                         java.util.function.Supplier<LocalDateTime> builtIn) {
        Object v = fieldMapping.resolveOrDefault(field, records, builtIn::get);
        if (v instanceof LocalDateTime dt) return dt;
        return parseDateTime(v, null);
    }

    private boolean mappedBoolean(com.asm.erpadapter.mapping.CanonicalField field,
                                  Map<String, Map<String, Object>> records,
                                  java.util.function.Supplier<Boolean> builtIn) {
        Object v = fieldMapping.resolveOrDefault(field, records, builtIn::get);
        if (v instanceof Boolean b) return b;
        if (v instanceof Number n) return n.doubleValue() != 0d;
        // A customer often flags readiness with a status word rather than a checkbox.
        if (v instanceof String str) {
            String t = str.trim().toLowerCase();
            return t.equals("1") || t.equals("true") || t.equals("yes") || t.equals("to deliver");
        }
        return false;
    }

    /** An empty bag is noise on the delivery card; null keeps the section hidden. */
    private static Map<String, Object> emptyToNull(Map<String, Object> m) {
        return m == null || m.isEmpty() ? null : m;
    }

    /** The documents in scope for a header mapping on this order. */
    private Map<String, Map<String, Object>> headerRecords(Map<String, Object> so,
                                                           Map<String, Object> customer,
                                                           Map<String, Object> address) {
        Map<String, Map<String, Object>> records = new HashMap<>();
        records.put("Sales Order", so);
        if (customer != null) records.put("Customer", customer);
        if (address != null) records.put("Address", address);
        return records;
    }

    /** Frappe stores dates as {@code yyyy-MM-dd} and times as {@code HH:mm:ss}. */
    private static final DateTimeFormatter D = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    private static final DateTimeFormatter T = DateTimeFormatter.ofPattern("HH:mm:ss");

    // ── Company scoping ──────────────────────────────────────────────────────────

    /**
     * Resolve the single company whose data we read. Fail-loud on ambiguity — never guess.
     * @throws ErpAdapterException if the instance has &gt;1 company and none is configured.
     */
    private String resolveCompany() {
        String configured = erp.companyScope();
        if (!configured.isBlank()) return configured;
        List<Map<String, Object>> companies = erp.getList("Company", List.of("name"), null, 0, "creation asc");
        if (companies.isEmpty()) return null;
        if (companies.size() == 1) return asString(companies.get(0).get("name"));
        List<String> names = companies.stream().map(c -> asString(c.get("name"))).toList();
        throw new ErpAdapterException(
                "ERPNext instance hosts multiple companies " + names + " — set 'company' in ERP settings "
                        + "to pick which one ASM should read (1 instance = 1 company).", 400);
    }

    private List<Object> companyFilter(String company) {
        return List.of("company", "=", company);
    }

    // ── Search Clients (manual create flow) ──────────────────────────────────────

    @Override
    public List<ErpClientDTO> searchClients(String search, int limit) {
        long start = System.currentTimeMillis();
        String term = search != null ? search.trim() : "";
        List<List<Object>> filters = new ArrayList<>();
        filters.add(List.of("disabled", "=", 0));
        if (!term.isEmpty()) filters.add(List.of("customer_name", "like", "%" + term + "%"));

        List<Map<String, Object>> rows = erp.getList("Customer",
                List.of("name", "customer_name", "mobile_no", "email_id"), filters, limit, "customer_name asc");

        List<ErpClientDTO> result = new ArrayList<>();
        for (Map<String, Object> r : rows) {
            String id = asString(r.get("name"));
            if (id == null) continue;
            // Customer carries no phone/email inline in most installs — they live on a linked Contact.
            // Best-effort from mobile_no/email_id when present; null otherwise (documented limitation).
            result.add(ErpClientDTO.builder()
                    .erpClientId(id)
                    .name(orEmpty(asString(r.get("customer_name"))))
                    .phone(asString(r.get("mobile_no")))
                    .email(asString(r.get("email_id")))
                    .build());
        }
        log.info("[erpnext] searchClients term='{}' count={} durationMs={}", term, result.size(), System.currentTimeMillis() - start);
        return result;
    }

    // ── Search Products (manual create flow) ─────────────────────────────────────

    @Override
    public List<ErpProductDTO> searchProducts(String search, int limit) {
        long start = System.currentTimeMillis();
        String term = search != null ? search.trim() : "";
        List<List<Object>> filters = new ArrayList<>();
        filters.add(List.of("disabled", "=", 0));
        filters.add(List.of("is_sales_item", "=", 1));
        if (!term.isEmpty()) filters.add(List.of("item_name", "like", "%" + term + "%"));

        List<Map<String, Object>> rows = erp.getList("Item",
                List.of("item_code", "item_name", "stock_uom", "standard_rate", "valuation_rate",
                        "weight_per_unit", "description", "is_sales_item"),
                filters, limit, "item_name asc");

        List<ErpProductDTO> result = new ArrayList<>();
        for (Map<String, Object> r : rows) {
            String sku = asString(r.get("item_code"));
            if (sku == null) continue;
            // Selling price lives in the Item Price doctype (price lists); fall back to standard/valuation
            // rate as an indicative price without a second per-item fetch.
            BigDecimal price = asBigDecimal(r.get("standard_rate"));
            if (price == null || price.signum() == 0) price = asBigDecimal(r.get("valuation_rate"));
            Double weight = asDouble(r.get("weight_per_unit"));
            result.add(ErpProductDTO.builder()
                    .erpProductId(sku)
                    .name(orEmpty(asString(r.get("item_name"))))
                    .sku(sku)
                    .price(price != null ? price.doubleValue() : 0.0)
                    .weightKg(weight != null ? weight : 0.0)
                    .available(asBool(r.get("is_sales_item")))
                    .description(asString(r.get("description")))
                    .build());
        }
        log.info("[erpnext] searchProducts term='{}' count={} durationMs={}", term, result.size(), System.currentTimeMillis() - start);
        return result;
    }

    // ── Pending orders = Sales Orders still to deliver ───────────────────────────

    /** Sales Order statuses that mean "confirmed, still awaiting delivery". */
    private static final List<Object> TO_DELIVER_STATUSES = List.of("To Deliver", "To Deliver and Bill");

    @Override
    public List<ErpPendingOrderSummaryDTO> getPendingOrders(int limit) {
        long start = System.currentTimeMillis();
        String company = resolveCompany();
        if (company == null) return List.of();

        List<List<Object>> filters = List.of(
                List.of("docstatus", "=", 1),          // confirmed sale order
                companyFilter(company),
                List.of("status", "in", TO_DELIVER_STATUSES));

        List<String> soFields = List.of("name", "customer", "customer_name", "contact_mobile", "transaction_date",
                "delivery_date", "grand_total", "currency", "set_warehouse", "total_qty", "per_delivered",
                "po_no", "payment_terms_template", "shipping_address_name", "customer_address");
        List<Map<String, Object>> rows = listWidened("Sales Order", soFields, filters, limit, "delivery_date asc");

        // Batch-resolve delivery addresses in ONE call (mirrors the Odoo adapter's partner batch), so the
        // list shows the destination without an N+1 per-order Address fetch.
        Map<String, Map<String, Object>> addrByName = batchAddresses(rows);
        Map<String, Map<String, Object>> customerByName = batchCustomers(rows);

        List<ErpPendingOrderSummaryDTO> result = new ArrayList<>();
        for (Map<String, Object> r : rows) {
            String so = asString(r.get("name"));
            if (so == null) continue;
            final String wh = asString(r.get("set_warehouse"));
            final Map<String, Object> addr = addrByName.get(
                    firstNonBlank(asString(r.get("shipping_address_name")), asString(r.get("customer_address"))));
            // Mapped here as well as in the preview: wiring only one of the two would show different
            // values for the same order depending on which screen you were looking at.
            Map<String, Map<String, Object>> records =
                    headerRecords(r, customerByName.get(asString(r.get("customer"))), addr);
            // A partially-delivered SO (per_delivered > 0) re-appearing here IS the reliquat/backorder.
            Double perDelivered = asDouble(r.get("per_delivered"));
            boolean isBackorder = perDelivered != null && perDelivered > 0;
            result.add(ErpPendingOrderSummaryDTO.builder()
                    .erpOrderId(mappedString(ERP_ORDER_ID, records, () -> so))
                    .saleOrderRef(mappedString(SALE_ORDER_REF, records, () -> so))
                    .customerRef(mappedString(CUSTOMER_REF, records, () -> asString(r.get("po_no"))))
                    .customerName(mappedString(CUSTOMER_NAME, records, () -> asString(r.get("customer_name"))))
                    .customerPhone(mappedString(CUSTOMER_PHONE, records, () -> asString(r.get("contact_mobile"))))
                    .deliveryAddress(mappedString(DELIVERY_ADDRESS, records,
                            () -> addr != null ? buildAddress(addr) : null))
                    .deliveryCity(mappedString(DELIVERY_CITY, records,
                            () -> addr != null ? asString(addr.get("city")) : null))
                    .deliveryPostalCode(mappedString(DELIVERY_POSTAL_CODE, records,
                            () -> addr != null ? asString(addr.get("pincode")) : null))
                    .totalAmount(mappedDecimal(TOTAL_AMOUNT, records, () -> asBigDecimal(r.get("grand_total"))))
                    .currency(mappedString(CURRENCY, records, () -> asString(r.get("currency"))))
                    // Default false: see CanonicalField.COD_REQUIRED.
                    .codRequired(mappedBoolean(COD_REQUIRED, records, () -> false))
                    .codAmount(mappedDecimal(COD_AMOUNT, records, () -> asBigDecimal(r.get("grand_total"))))
                    .warehouseCode(mappedString(WAREHOUSE_CODE, records, () -> wh))
                    .warehouseName(mappedString(WAREHOUSE_NAME, records, () -> wh))
                    .ready(mappedBoolean(READY, records, () -> true))
                    .priority(mappedString(PRIORITY, records, () -> "NORMAL"))
                    .backorder(isBackorder)   // reliquat badge; no originBl — the row already shows the SO (self-reference)
                    .scheduledAt(mappedDateTime(SCHEDULED_AT, records, () -> parseDateTime(r.get("delivery_date"), null)))
                    .dateOrder(mappedDateTime(DATE_ORDER, records, () -> parseDateTime(r.get("transaction_date"), null)))
                    .build());
        }
        log.info("[erpnext] getPendingOrders (SO to-deliver) company='{}' count={} durationMs={}", company, result.size(), System.currentTimeMillis() - start);
        return result;
    }

    @Override
    public ErpPendingOrderPreviewDTO getPendingOrderPreview(String erpOrderId) {
        if (erpOrderId == null || erpOrderId.isBlank()) return null;
        Map<String, Object> so = erp.getDoc("Sales Order", erpOrderId);
        if (so == null) return null;

        List<ErpOrderItemDTO> items = new ArrayList<>();
        int totalQty = 0;
        BigDecimal totalWeight = BigDecimal.ZERO;
        String firstWarehouse = null;
        Object rawItems = so.get("items");

        // Frappe puts tax on the document, not on the line: a line has a rate, the order has a
        // grand_total, and nothing in between. The taxed unit price is therefore derived by spreading
        // the difference across the lines in proportion to their own value — exact whenever the tax is
        // itself proportional, which covers VAT.
        final BigDecimal taxFactor = taxFactorOf(so, rawItems);
        if (rawItems instanceof List<?> lines) {
            for (Object o : lines) {
                if (!(o instanceof Map<?, ?> line)) continue;
                @SuppressWarnings("unchecked")
                Map<String, Object> li = (Map<String, Object>) line;
                Integer qty = asInt(li.get("qty"));
                Integer delivered = asInt(li.get("delivered_qty"));
                int remaining = (qty != null ? qty : 0) - (delivered != null ? delivered : 0);
                if (remaining <= 0) continue;              // this line is already fully delivered
                // Line scope: a bare path is read against the order row, and the Item is fetched only
                // when the tenant mapped something onto it.
                Map<String, Map<String, Object>> lineRecords = new HashMap<>();
                lineRecords.put("Sales Order Item", li);
                lineRecords.put("Sales Order", so);
                if (!fieldMapping.extraFieldsFor("Item").isEmpty()) {
                    Map<String, Object> item = erp.getDoc("Item", asString(li.get("item_code")));
                    if (item != null) lineRecords.put("Item", item);
                }

                final int left = remaining;
                Integer mappedQty = mappedInt(ITEM_QUANTITY, lineRecords, () -> left);
                int quantity = mappedQty != null ? mappedQty : left;
                BigDecimal unitWeight = mappedDecimal(ITEM_UNIT_WEIGHT_KG, lineRecords,
                        () -> asBigDecimal(li.get("weight_per_unit")));
                items.add(ErpOrderItemDTO.builder()
                        .name(mappedString(ITEM_NAME, lineRecords, () -> asString(li.get("item_name"))))
                        .sku(mappedString(ITEM_SKU, lineRecords, () -> asString(li.get("item_code"))))
                        .quantity(quantity)                // what's left to deliver (handles partial/backorder)
                        .unitPrice(mappedDecimal(ITEM_UNIT_PRICE, lineRecords, () -> asBigDecimal(li.get("rate"))))
                        .unitPriceTtc(taxFactor == null ? null
                                : applyFactor(asBigDecimal(li.get("rate")), taxFactor))
                        .unitWeightKg(unitWeight)
                        .productType(mappedString(ITEM_PRODUCT_TYPE, lineRecords, () -> asString(li.get("item_group"))))
                        .build());
                totalQty += quantity;
                if (unitWeight != null) totalWeight = totalWeight.add(unitWeight.multiply(BigDecimal.valueOf(quantity)));
                if (firstWarehouse == null) firstWarehouse = asString(li.get("warehouse"));
            }
        }

        // Delivery address: resolve the linked Address doc and build a CLEAN address from its structured
        // fields — never the raw address_display, which is HTML (<br> lines). Order: SO shipping address,
        // then customer address, then the customer's default Address. HTML display is a last resort.
        String address = null;
        String city = null;
        String addrName = firstNonBlank(asString(so.get("shipping_address_name")), asString(so.get("customer_address")));
        if (addrName == null) addrName = defaultCustomerAddress(asString(so.get("customer")));
        Map<String, Object> addr = null;
        if (addrName != null) {
            addr = erp.getDoc("Address", addrName);
            if (addr != null) {
                city = asString(addr.get("city"));
                address = buildAddress(addr);
            }
        }
        if (address == null) address = stripHtml(asString(so.get("address_display")));

        // Kept so a mapping can name Customer: or Address: explicitly. Fetched only when the tenant
        // has actually mapped something onto the customer — an unmapped tenant pays nothing.
        Map<String, Object> customer = null;
        if (!fieldMapping.extraFieldsFor("Customer").isEmpty()) {
            customer = erp.getDoc("Customer", asString(so.get("customer")));
        }
        Map<String, Map<String, Object>> records = headerRecords(so, customer, addr);
        final String builtAddress = address;
        final String builtCity = city;
        final String builtPostalCode = addr != null ? asString(addr.get("pincode")) : null;
        final String builtWarehouse = firstNonBlank(asString(so.get("set_warehouse")), firstWarehouse);

        return ErpPendingOrderPreviewDTO.builder()
                .source("ERPNEXT")
                .erpOrderId(mappedString(ERP_ORDER_ID, records, () -> erpOrderId))
                .saleOrderRef(mappedString(SALE_ORDER_REF, records, () -> erpOrderId))
                // No delivery note exists until the order is delivered, so there is no number to
                // read; a tenant that has one elsewhere can map it.
                .blNumber(mappedString(BL_NUMBER, records, () -> null))
                .customerRef(mappedString(CUSTOMER_REF, records, () -> asString(so.get("po_no"))))
                .customerName(mappedString(CUSTOMER_NAME, records, () -> asString(so.get("customer_name"))))
                .customerPhone(mappedString(CUSTOMER_PHONE, records, () -> asString(so.get("contact_mobile"))))
                .deliveryAddress(mappedString(DELIVERY_ADDRESS, records, () -> builtAddress))
                .deliveryCity(mappedString(DELIVERY_CITY, records, () -> builtCity))
                .deliveryPostalCode(mappedString(DELIVERY_POSTAL_CODE, records, () -> builtPostalCode))
                .deliveryInstructions(mappedString(DELIVERY_INSTRUCTIONS, records, () -> asString(so.get("instructions"))))
                .totalAmount(mappedDecimal(TOTAL_AMOUNT, records, () -> asBigDecimal(so.get("grand_total"))))
                .currency(mappedString(CURRENCY, records, () -> asString(so.get("currency"))))
                // Default false: see CanonicalField.COD_REQUIRED.
                .codRequired(mappedBoolean(COD_REQUIRED, records, () -> false))
                .codAmount(mappedDecimal(COD_AMOUNT, records, () -> asBigDecimal(so.get("grand_total"))))
                .priority(mappedString(PRIORITY, records, () -> "NORMAL"))
                .scheduledAt(mappedDateTime(SCHEDULED_AT, records, () -> parseDateTime(so.get("delivery_date"), null)))
                .dateOrder(mappedDateTime(DATE_ORDER, records, () -> parseDateTime(so.get("transaction_date"), null)))
                .items(items)
                .totalQuantity(totalQty)
                .totalWeightKg(totalWeight)
                .warehouseCode(mappedString(WAREHOUSE_CODE, records, () -> builtWarehouse))
                .warehouseName(mappedString(WAREHOUSE_NAME, records, () -> builtWarehouse))
                .ready(mappedBoolean(READY, records, () -> true))
                // ERP values ASM has no field of its own for.
                .customFields(emptyToNull(fieldMapping.resolveCustomFields(records)))
                .build();
    }

    // ── Warehouses (source depots) ───────────────────────────────────────────────

    @Override
    public List<ErpWarehouseDTO> getWarehouses() {
        long start = System.currentTimeMillis();
        String company = resolveCompany();
        if (company == null) return List.of();

        List<List<Object>> filters = List.of(
                List.of("is_group", "=", 0),          // skip parent folders ("All Warehouses")
                List.of("disabled", "=", 0),
                companyFilter(company));

        List<Map<String, Object>> rows = erp.getList("Warehouse",
                List.of("name", "warehouse_name", "warehouse_type"), filters, 0, "name asc");

        List<ErpWarehouseDTO> result = new ArrayList<>();
        for (Map<String, Object> w : rows) {
            // Drop logical transit warehouses (Goods In Transit) — not physical dispatch depots.
            // Filtered in Java, not in the query: a SQL "warehouse_type != 'Transit'" would also exclude
            // the physical warehouses whose type is NULL. (WIP has a NULL type too → left for the admin
            // to uncheck at the Bind step; only Transit is auto-excluded here.)
            if ("Transit".equalsIgnoreCase(asString(w.get("warehouse_type")))) continue;
            String code = asString(w.get("name"));   // the warehouse name IS the stable key ASM maps to a depot
            if (code == null) continue;
            // ERPNext warehouses carry no coordinates → ASM geocodes / the admin sets GPS at bind time.
            result.add(ErpWarehouseDTO.builder()
                    .erpWarehouseId(code)
                    .code(code)
                    .name(firstNonBlank(asString(w.get("warehouse_name")), code))
                    .latitude(null)
                    .longitude(null)
                    .build());
        }
        log.info("[erpnext] getWarehouses company='{}' count={} durationMs={}", company, result.size(), System.currentTimeMillis() - start);
        return result;
    }

    // ── Picking ref (backorder linking) — DN name IS the ref ─────────────────────

    @Override
    public String getPickingRef(String pickingId) {
        // In ERPNext the Delivery Note name is both the id and the human ref — passthrough.
        return pickingId;
    }

    // ── Company (tenant's own selling entity) ────────────────────────────────────

    @Override
    public ErpCompanyDTO getCompany() {
        String company = resolveCompany();
        if (company == null) return null;
        Map<String, Object> c = erp.getDoc("Company", company);
        if (c == null) return null;

        // Company address is a linked Address doc (no inline street/city); best-effort resolve.
        String address = null;
        String city = null;
        Map<String, Object> addr = firstCompanyAddress(company);
        if (addr != null) {
            address = buildAddress(addr);
            city = asString(addr.get("city"));
        }

        return ErpCompanyDTO.builder()
                .name(firstNonBlank(asString(c.get("company_name")), company))
                .address(address)
                .city(city)
                .phone(asString(c.get("phone_no")))
                .email(asString(c.get("email")))
                .vat(asString(c.get("tax_id")))
                .website(asString(c.get("website")))
                .logo(asString(c.get("company_logo")))
                .build();
    }

    /** Fetch the company's primary Address via the Dynamic Link on the Address doctype (best-effort). */
    private Map<String, Object> firstCompanyAddress(String company) {
        // Address links to its owner through the child table "Dynamic Link"; filter by link_name.
        List<Map<String, Object>> rows = erp.getList("Address",
                List.of("name"),
                List.of(List.of("link_name", "=", company)),
                1, "creation asc");
        if (rows.isEmpty()) return null;
        return erp.getDoc("Address", asString(rows.get(0).get("name")));
    }

    /** One batch fetch of the Sales Orders' shipping addresses → address name → [address, city]. */
    private Map<String, Map<String, Object>> batchAddresses(List<Map<String, Object>> soRows) {
        List<Object> names = new ArrayList<>();
        for (Map<String, Object> r : soRows) {
            String n = firstNonBlank(asString(r.get("shipping_address_name")), asString(r.get("customer_address")));
            if (n != null && !names.contains(n)) names.add(n);
        }
        if (names.isEmpty()) return Map.of();
        List<Map<String, Object>> addrs = listWidened("Address",
                List.of("name", "address_line1", "address_line2", "city", "pincode"),
                List.of(List.of("name", "in", names)), 0, null);
        Map<String, Map<String, Object>> byName = new HashMap<>();
        for (Map<String, Object> a : addrs) {
            String n = asString(a.get("name"));
            if (n != null) byName.put(n, a);
        }
        return byName;
    }

    /**
     * The adapter's own field list plus whatever this tenant mapped onto {@code doctype}.
     *
     * <p>Without this a mapping points at a field the request never asked for, so the value is
     * absent from the row and resolves to nothing — and the integrator cannot tell "my ERP field is
     * empty" from "the system never fetched it". Only needed on the list reads; {@code getDoc}
     * already returns the whole document.
     */
    private List<String> widened(List<String> base, String doctype) {
        java.util.LinkedHashSet<String> all = new java.util.LinkedHashSet<>(base);
        all.addAll(fieldMapping.extraFieldsFor(doctype));
        return List.copyOf(all);
    }

    /**
     * List {@code doctype} asking for the mapped fields too, falling back to the base list if that is
     * refused.
     *
     * <p>Frappe rejects the <em>whole query</em> when one requested field does not exist — so a single
     * bad path would empty the pending-orders screen rather than blank one value, and the screen would
     * say the ERP has no orders. The retry keeps that failure proportionate: the mapping stops
     * resolving in the list, the orders still arrive.
     */
    private List<Map<String, Object>> listWidened(String doctype, List<String> base,
                                                  List<List<Object>> filters, int limit, String orderBy) {
        List<String> fields = widened(base, doctype);
        if (fields.size() == base.size()) return erp.getList(doctype, base, filters, limit, orderBy);
        try {
            return erp.getListStrict(doctype, fields, filters, limit, orderBy);
        } catch (Exception e) {
            log.warn("[erpnext] {} list refused the mapped fields, retrying without them: {}",
                    doctype, e.getMessage());
            return erp.getList(doctype, base, filters, limit, orderBy);
        }
    }

    /**
     * The customer documents these orders point at, in one call — and only when the tenant has
     * actually mapped something onto Customer.
     *
     * <p>Mirrors {@link #batchAddresses}. Without it a Customer-scoped mapping resolved on the
     * preview and came back blank in the list, so the same order showed two different values
     * depending on which screen you were looking at.
     */
    private Map<String, Map<String, Object>> batchCustomers(List<Map<String, Object>> soRows) {
        if (fieldMapping.extraFieldsFor("Customer").isEmpty()) return Map.of();
        List<Object> names = new ArrayList<>();
        for (Map<String, Object> r : soRows) {
            String n = asString(r.get("customer"));
            if (n != null && !names.contains(n)) names.add(n);
        }
        if (names.isEmpty()) return Map.of();
        Map<String, Map<String, Object>> byName = new HashMap<>();
        for (Map<String, Object> c : listWidened("Customer", List.of("name", "customer_name"),
                List.of(List.of("name", "in", names)), 0, null)) {
            String n = asString(c.get("name"));
            if (n != null) byName.put(n, c);
        }
        return byName;
    }

    /** Resolve the customer's shipping (or primary) Address name via the Dynamic Link (best-effort). */
    private String defaultCustomerAddress(String customer) {
        if (customer == null) return null;
        List<Map<String, Object>> rows = erp.getList("Address",
                List.of("name", "is_shipping_address"),
                List.of(List.of("link_name", "=", customer)),
                10, "is_shipping_address desc");
        if (rows.isEmpty()) return null;
        for (Map<String, Object> r : rows) if (asBool(r.get("is_shipping_address"))) return asString(r.get("name"));
        return asString(rows.get(0).get("name"));
    }

    // ── Small helpers ────────────────────────────────────────────────────────────

    private static LocalDateTime parseDateTime(Object date, Object time) {
        String d = asString(date);
        if (d == null) return null;
        try {
            LocalDate ld = LocalDate.parse(d.length() > 10 ? d.substring(0, 10) : d, D);
            String t = asString(time);
            LocalTime lt = LocalTime.MIDNIGHT;
            if (t != null) {
                try { lt = LocalTime.parse(t.length() > 8 ? t.substring(0, 8) : t, T); }
                catch (Exception ignored) { /* keep midnight */ }
            }
            return LocalDateTime.of(ld, lt);
        } catch (Exception e) {
            return null;
        }
    }

    private static String buildAddress(Map<String, Object> addr) {
        if (addr == null) return null;
        List<String> parts = new ArrayList<>();
        add(parts, asString(addr.get("address_line1")));
        add(parts, asString(addr.get("address_line2")));
        add(parts, asString(addr.get("pincode")));
        String joined = String.join(", ", parts);
        return joined.isBlank() ? null : joined;
    }

    private static void add(List<String> parts, String v) {
        if (v != null && !v.isBlank()) parts.add(v);
    }

    /**
     * By how much the taxed total exceeds the sum of the untaxed lines, as a multiplier.
     *
     * <p>Returns {@code null} — no taxed price at all — rather than 1 when the order gives nothing to
     * work from. A factor of 1 would be a claim that this order carries no tax, which is a different
     * statement from not knowing, and the difference is money a driver would fail to collect.
     */
    private static BigDecimal taxFactorOf(Map<String, Object> so, Object rawItems) {
        BigDecimal grandTotal = asBigDecimal(so.get("grand_total"));
        if (grandTotal == null || grandTotal.signum() <= 0 || !(rawItems instanceof List<?> lines)) return null;

        BigDecimal untaxed = BigDecimal.ZERO;
        for (Object o : lines) {
            if (!(o instanceof Map<?, ?> line)) continue;
            @SuppressWarnings("unchecked")
            Map<String, Object> li = (Map<String, Object>) line;
            BigDecimal rate = asBigDecimal(li.get("rate"));
            Integer qty = asInt(li.get("qty"));
            if (rate == null || qty == null) return null;   // one unpriced line and the ratio is a guess
            untaxed = untaxed.add(rate.multiply(BigDecimal.valueOf(qty)));
        }
        if (untaxed.signum() <= 0) return null;
        return grandTotal.divide(untaxed, 8, java.math.RoundingMode.HALF_UP);
    }

    private static BigDecimal applyFactor(BigDecimal rate, BigDecimal factor) {
        return rate == null ? null : rate.multiply(factor).setScale(6, java.math.RoundingMode.HALF_UP);
    }

    /** Flatten Frappe's HTML {@code address_display} (&lt;br&gt; lines) into a comma-separated string. */
    private static String stripHtml(String html) {
        if (html == null) return null;
        String s = html.replaceAll("(?i)<br\\s*/?>", ", ").replaceAll("<[^>]+>", " ")
                .replaceAll("\\s+", " ").trim();
        s = s.replaceAll("(,\\s*)+", ", ").replaceAll("^,\\s*|,\\s*$", "").trim();
        return s.isBlank() ? null : s;
    }

    private static String firstNonBlank(String... vals) {
        for (String v : vals) if (v != null && !v.isBlank()) return v;
        return null;
    }

    private static String orEmpty(String s) {
        return s != null ? s : "";
    }
}
