package com.asm.erpadapter.adapter.erpnext;

import com.asm.erpadapter.dto.*;
import com.asm.erpadapter.exception.ErpAdapterException;
import com.asm.erpadapter.port.ErpLookupPort;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static com.asm.erpadapter.adapter.erpnext.ErpNextRestClient.*;

/**
 * ERPNext implementation of {@link ErpLookupPort} (ERPNext v15/16, Frappe REST).
 *
 * <p><b>Import unit = the Sales Order to deliver.</b> Unlike Odoo (which auto-creates an outgoing
 * {@code stock.picking} on confirmation), ERPNext has no pre-created "ready" delivery document — the
 * Delivery Note is created only <em>at shipping time</em> from the Sales Order. So the "ready to
 * deliver" queue is the set of confirmed Sales Orders still awaiting delivery ({@code status} in
 * "To Deliver"/"To Deliver and Bill"). ASM imports the Sales Order; on delivery it creates + submits
 * the Delivery Note (Phase B write-back = the analog of Odoo {@code button_validate}). {@code blNumber}
 * is therefore assigned by ERPNext only when ASM delivers, not at import.
 *
 * <p><b>Company scoping (1 instance = 1 company):</b> an ERPNext instance can host several companies
 * (a bare install already ships a "(Demo)" company). Every read is scoped to a single company resolved
 * by {@link #resolveCompany()}: the configured {@code company} key, else the only company, else a
 * loud error asking the admin to pick one. Never a silent {@code first()}.
 *
 * <p><b>ASM owns what the ERP can't standardize:</b> warehouse GPS (ERPNext warehouses carry no
 * coordinates → ASM geocodes) and the BL PDF (generated by ASM; {@code blNumber} is only the ERP
 * reference for reconciliation).
 */
@Component("erpnextLookup")
@RequiredArgsConstructor
@Slf4j
public class ErpNextLookupAdapter implements ErpLookupPort {

    private final ErpNextRestClient erp;

    /** Frappe stores dates as {@code yyyy-MM-dd} and times as {@code HH:mm:ss}. */
    private static final DateTimeFormatter D = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    private static final DateTimeFormatter T = DateTimeFormatter.ofPattern("HH:mm:ss");

    // ── Company scoping ──────────────────────────────────────────────────────────

    /**
     * Resolve the single company whose data we read. Fail-loud on ambiguity — never guess.
     * @throws ErpAdapterException if the instance has &gt;1 company and none is configured.
     */
    private String resolveCompany() {
        String configured = erp.companyScope();
        if (!configured.isBlank()) return configured;
        List<Map<String, Object>> companies = erp.getList("Company", List.of("name"), null, 0, "creation asc");
        if (companies.isEmpty()) return null;
        if (companies.size() == 1) return asString(companies.get(0).get("name"));
        List<String> names = companies.stream().map(c -> asString(c.get("name"))).toList();
        throw new ErpAdapterException(
                "ERPNext instance hosts multiple companies " + names + " — set 'company' in ERP settings "
                        + "to pick which one ASM should read (1 instance = 1 company).", 400);
    }

    private List<Object> companyFilter(String company) {
        return List.of("company", "=", company);
    }

    // ── Search Clients (manual create flow) ──────────────────────────────────────

    @Override
    public List<ErpClientDTO> searchClients(String search, int limit) {
        long start = System.currentTimeMillis();
        String term = search != null ? search.trim() : "";
        List<List<Object>> filters = new ArrayList<>();
        filters.add(List.of("disabled", "=", 0));
        if (!term.isEmpty()) filters.add(List.of("customer_name", "like", "%" + term + "%"));

        List<Map<String, Object>> rows = erp.getList("Customer",
                List.of("name", "customer_name", "mobile_no", "email_id"), filters, limit, "customer_name asc");

        List<ErpClientDTO> result = new ArrayList<>();
        for (Map<String, Object> r : rows) {
            String id = asString(r.get("name"));
            if (id == null) continue;
            // Customer carries no phone/email inline in most installs — they live on a linked Contact.
            // Best-effort from mobile_no/email_id when present; null otherwise (documented limitation).
            result.add(ErpClientDTO.builder()
                    .erpClientId(id)
                    .name(orEmpty(asString(r.get("customer_name"))))
                    .phone(asString(r.get("mobile_no")))
                    .email(asString(r.get("email_id")))
                    .build());
        }
        log.info("[erpnext] searchClients term='{}' count={} durationMs={}", term, result.size(), System.currentTimeMillis() - start);
        return result;
    }

    // ── Search Products (manual create flow) ─────────────────────────────────────

    @Override
    public List<ErpProductDTO> searchProducts(String search, int limit) {
        long start = System.currentTimeMillis();
        String term = search != null ? search.trim() : "";
        List<List<Object>> filters = new ArrayList<>();
        filters.add(List.of("disabled", "=", 0));
        filters.add(List.of("is_sales_item", "=", 1));
        if (!term.isEmpty()) filters.add(List.of("item_name", "like", "%" + term + "%"));

        List<Map<String, Object>> rows = erp.getList("Item",
                List.of("item_code", "item_name", "stock_uom", "standard_rate", "valuation_rate",
                        "weight_per_unit", "description", "is_sales_item"),
                filters, limit, "item_name asc");

        List<ErpProductDTO> result = new ArrayList<>();
        for (Map<String, Object> r : rows) {
            String sku = asString(r.get("item_code"));
            if (sku == null) continue;
            // Selling price lives in the Item Price doctype (price lists); fall back to standard/valuation
            // rate as an indicative price without a second per-item fetch.
            BigDecimal price = asBigDecimal(r.get("standard_rate"));
            if (price == null || price.signum() == 0) price = asBigDecimal(r.get("valuation_rate"));
            Double weight = asDouble(r.get("weight_per_unit"));
            result.add(ErpProductDTO.builder()
                    .erpProductId(sku)
                    .name(orEmpty(asString(r.get("item_name"))))
                    .sku(sku)
                    .price(price != null ? price.doubleValue() : 0.0)
                    .weightKg(weight != null ? weight : 0.0)
                    .available(asBool(r.get("is_sales_item")))
                    .description(asString(r.get("description")))
                    .build());
        }
        log.info("[erpnext] searchProducts term='{}' count={} durationMs={}", term, result.size(), System.currentTimeMillis() - start);
        return result;
    }

    // ── Pending orders = Sales Orders still to deliver ───────────────────────────

    /** Sales Order statuses that mean "confirmed, still awaiting delivery". */
    private static final List<Object> TO_DELIVER_STATUSES = List.of("To Deliver", "To Deliver and Bill");

    @Override
    public List<ErpPendingOrderSummaryDTO> getPendingOrders(int limit) {
        long start = System.currentTimeMillis();
        String company = resolveCompany();
        if (company == null) return List.of();

        List<List<Object>> filters = List.of(
                List.of("docstatus", "=", 1),          // confirmed sale order
                companyFilter(company),
                List.of("status", "in", TO_DELIVER_STATUSES));

        List<Map<String, Object>> rows = erp.getList("Sales Order",
                List.of("name", "customer_name", "contact_mobile", "transaction_date", "delivery_date",
                        "grand_total", "currency", "set_warehouse", "total_qty", "per_delivered",
                        "shipping_address_name", "customer_address"),
                filters, limit, "delivery_date asc");

        // Batch-resolve delivery addresses in ONE call (mirrors the Odoo adapter's partner batch), so the
        // list shows the destination without an N+1 per-order Address fetch.
        Map<String, String[]> addrByName = batchAddresses(rows);

        List<ErpPendingOrderSummaryDTO> result = new ArrayList<>();
        for (Map<String, Object> r : rows) {
            String so = asString(r.get("name"));
            if (so == null) continue;
            String wh = asString(r.get("set_warehouse"));
            String[] addr = addrByName.get(firstNonBlank(asString(r.get("shipping_address_name")), asString(r.get("customer_address"))));
            // A partially-delivered SO (per_delivered > 0) re-appearing here IS the reliquat/backorder.
            Double perDelivered = asDouble(r.get("per_delivered"));
            boolean isBackorder = perDelivered != null && perDelivered > 0;
            result.add(ErpPendingOrderSummaryDTO.builder()
                    .erpOrderId(so)                        // import identity = the Sales Order (no BL until delivery)
                    .saleOrderRef(so)
                    .customerName(asString(r.get("customer_name")))
                    .customerPhone(asString(r.get("contact_mobile")))
                    .deliveryAddress(addr != null ? addr[0] : null)
                    .deliveryCity(addr != null ? addr[1] : null)
                    .totalAmount(asBigDecimal(r.get("grand_total")))
                    .currency(asString(r.get("currency")))
                    .warehouseCode(wh)
                    .warehouseName(wh)                     // ERPNext warehouse name == its code (natural key)
                    .ready(true)
                    .backorder(isBackorder)
                    .originBl(isBackorder ? so : null)
                    .scheduledAt(parseDateTime(r.get("delivery_date"), null))
                    .dateOrder(parseDateTime(r.get("transaction_date"), null))
                    .build());
        }
        log.info("[erpnext] getPendingOrders (SO to-deliver) company='{}' count={} durationMs={}", company, result.size(), System.currentTimeMillis() - start);
        return result;
    }

    @Override
    public ErpPendingOrderPreviewDTO getPendingOrderPreview(String erpOrderId) {
        if (erpOrderId == null || erpOrderId.isBlank()) return null;
        Map<String, Object> so = erp.getDoc("Sales Order", erpOrderId);
        if (so == null) return null;

        List<ErpOrderItemDTO> items = new ArrayList<>();
        int totalQty = 0;
        BigDecimal totalWeight = BigDecimal.ZERO;
        String firstWarehouse = null;
        Object rawItems = so.get("items");
        if (rawItems instanceof List<?> lines) {
            for (Object o : lines) {
                if (!(o instanceof Map<?, ?> line)) continue;
                @SuppressWarnings("unchecked")
                Map<String, Object> li = (Map<String, Object>) line;
                Integer qty = asInt(li.get("qty"));
                Integer delivered = asInt(li.get("delivered_qty"));
                int remaining = (qty != null ? qty : 0) - (delivered != null ? delivered : 0);
                if (remaining <= 0) continue;              // this line is already fully delivered
                BigDecimal unitWeight = asBigDecimal(li.get("weight_per_unit"));
                items.add(ErpOrderItemDTO.builder()
                        .name(asString(li.get("item_name")))
                        .sku(asString(li.get("item_code")))
                        .quantity(remaining)               // what's left to deliver (handles partial/backorder)
                        .unitPrice(asBigDecimal(li.get("rate")))
                        .unitWeightKg(unitWeight)
                        .build());
                totalQty += remaining;
                if (unitWeight != null) totalWeight = totalWeight.add(unitWeight.multiply(BigDecimal.valueOf(remaining)));
                if (firstWarehouse == null) firstWarehouse = asString(li.get("warehouse"));
            }
        }

        // Delivery address: resolve the linked Address doc and build a CLEAN address from its structured
        // fields — never the raw address_display, which is HTML (<br> lines). Order: SO shipping address,
        // then customer address, then the customer's default Address. HTML display is a last resort.
        String address = null;
        String city = null;
        String addrName = firstNonBlank(asString(so.get("shipping_address_name")), asString(so.get("customer_address")));
        if (addrName == null) addrName = defaultCustomerAddress(asString(so.get("customer")));
        if (addrName != null) {
            Map<String, Object> addr = erp.getDoc("Address", addrName);
            if (addr != null) {
                city = asString(addr.get("city"));
                address = buildAddress(addr);
            }
        }
        if (address == null) address = stripHtml(asString(so.get("address_display")));

        String warehouse = firstNonBlank(asString(so.get("set_warehouse")), firstWarehouse);
        return ErpPendingOrderPreviewDTO.builder()
                .source("ERPNEXT")
                .erpOrderId(erpOrderId)                     // = Sales Order ref; blNumber assigned at delivery
                .saleOrderRef(erpOrderId)
                .customerName(asString(so.get("customer_name")))
                .customerPhone(asString(so.get("contact_mobile")))
                .deliveryAddress(address)
                .deliveryCity(city)
                .deliveryInstructions(asString(so.get("instructions")))
                .totalAmount(asBigDecimal(so.get("grand_total")))
                .currency(asString(so.get("currency")))
                .scheduledAt(parseDateTime(so.get("delivery_date"), null))
                .dateOrder(parseDateTime(so.get("transaction_date"), null))
                .items(items)
                .totalQuantity(totalQty)
                .totalWeightKg(totalWeight)
                .warehouseCode(warehouse)
                .warehouseName(warehouse)
                .ready(true)
                .build();
    }

    // ── Warehouses (source depots) ───────────────────────────────────────────────

    @Override
    public List<ErpWarehouseDTO> getWarehouses() {
        long start = System.currentTimeMillis();
        String company = resolveCompany();
        if (company == null) return List.of();

        List<List<Object>> filters = List.of(
                List.of("is_group", "=", 0),          // skip parent folders ("All Warehouses")
                List.of("disabled", "=", 0),
                companyFilter(company));

        List<Map<String, Object>> rows = erp.getList("Warehouse",
                List.of("name", "warehouse_name", "warehouse_type"), filters, 0, "name asc");

        List<ErpWarehouseDTO> result = new ArrayList<>();
        for (Map<String, Object> w : rows) {
            // Drop logical transit warehouses (Goods In Transit) — not physical dispatch depots.
            // Filtered in Java, not in the query: a SQL "warehouse_type != 'Transit'" would also exclude
            // the physical warehouses whose type is NULL. (WIP has a NULL type too → left for the admin
            // to uncheck at the Bind step; only Transit is auto-excluded here.)
            if ("Transit".equalsIgnoreCase(asString(w.get("warehouse_type")))) continue;
            String code = asString(w.get("name"));   // the warehouse name IS the stable key ASM maps to a depot
            if (code == null) continue;
            // ERPNext warehouses carry no coordinates → ASM geocodes / the admin sets GPS at bind time.
            result.add(ErpWarehouseDTO.builder()
                    .erpWarehouseId(code)
                    .code(code)
                    .name(firstNonBlank(asString(w.get("warehouse_name")), code))
                    .latitude(null)
                    .longitude(null)
                    .build());
        }
        log.info("[erpnext] getWarehouses company='{}' count={} durationMs={}", company, result.size(), System.currentTimeMillis() - start);
        return result;
    }

    // ── Picking ref (backorder linking) — DN name IS the ref ─────────────────────

    @Override
    public String getPickingRef(String pickingId) {
        // In ERPNext the Delivery Note name is both the id and the human ref — passthrough.
        return pickingId;
    }

    // ── Company (tenant's own selling entity) ────────────────────────────────────

    @Override
    public ErpCompanyDTO getCompany() {
        String company = resolveCompany();
        if (company == null) return null;
        Map<String, Object> c = erp.getDoc("Company", company);
        if (c == null) return null;

        // Company address is a linked Address doc (no inline street/city); best-effort resolve.
        String address = null;
        String city = null;
        Map<String, Object> addr = firstCompanyAddress(company);
        if (addr != null) {
            address = buildAddress(addr);
            city = asString(addr.get("city"));
        }

        return ErpCompanyDTO.builder()
                .name(firstNonBlank(asString(c.get("company_name")), company))
                .address(address)
                .city(city)
                .phone(asString(c.get("phone_no")))
                .email(asString(c.get("email")))
                .vat(asString(c.get("tax_id")))
                .website(asString(c.get("website")))
                .logo(asString(c.get("company_logo")))
                .build();
    }

    /** Fetch the company's primary Address via the Dynamic Link on the Address doctype (best-effort). */
    private Map<String, Object> firstCompanyAddress(String company) {
        // Address links to its owner through the child table "Dynamic Link"; filter by link_name.
        List<Map<String, Object>> rows = erp.getList("Address",
                List.of("name"),
                List.of(List.of("link_name", "=", company)),
                1, "creation asc");
        if (rows.isEmpty()) return null;
        return erp.getDoc("Address", asString(rows.get(0).get("name")));
    }

    /** One batch fetch of the Sales Orders' shipping addresses → address name → [address, city]. */
    private Map<String, String[]> batchAddresses(List<Map<String, Object>> soRows) {
        List<Object> names = new ArrayList<>();
        for (Map<String, Object> r : soRows) {
            String n = firstNonBlank(asString(r.get("shipping_address_name")), asString(r.get("customer_address")));
            if (n != null && !names.contains(n)) names.add(n);
        }
        if (names.isEmpty()) return Map.of();
        List<Map<String, Object>> addrs = erp.getList("Address",
                List.of("name", "address_line1", "address_line2", "city", "pincode"),
                List.of(List.of("name", "in", names)), 0, null);
        Map<String, String[]> byName = new HashMap<>();
        for (Map<String, Object> a : addrs) {
            String n = asString(a.get("name"));
            if (n != null) byName.put(n, new String[]{buildAddress(a), asString(a.get("city"))});
        }
        return byName;
    }

    /** Resolve the customer's shipping (or primary) Address name via the Dynamic Link (best-effort). */
    private String defaultCustomerAddress(String customer) {
        if (customer == null) return null;
        List<Map<String, Object>> rows = erp.getList("Address",
                List.of("name", "is_shipping_address"),
                List.of(List.of("link_name", "=", customer)),
                10, "is_shipping_address desc");
        if (rows.isEmpty()) return null;
        for (Map<String, Object> r : rows) if (asBool(r.get("is_shipping_address"))) return asString(r.get("name"));
        return asString(rows.get(0).get("name"));
    }

    // ── Small helpers ────────────────────────────────────────────────────────────

    private static LocalDateTime parseDateTime(Object date, Object time) {
        String d = asString(date);
        if (d == null) return null;
        try {
            LocalDate ld = LocalDate.parse(d.length() > 10 ? d.substring(0, 10) : d, D);
            String t = asString(time);
            LocalTime lt = LocalTime.MIDNIGHT;
            if (t != null) {
                try { lt = LocalTime.parse(t.length() > 8 ? t.substring(0, 8) : t, T); }
                catch (Exception ignored) { /* keep midnight */ }
            }
            return LocalDateTime.of(ld, lt);
        } catch (Exception e) {
            return null;
        }
    }

    private static String buildAddress(Map<String, Object> addr) {
        if (addr == null) return null;
        List<String> parts = new ArrayList<>();
        add(parts, asString(addr.get("address_line1")));
        add(parts, asString(addr.get("address_line2")));
        add(parts, asString(addr.get("pincode")));
        String joined = String.join(", ", parts);
        return joined.isBlank() ? null : joined;
    }

    private static void add(List<String> parts, String v) {
        if (v != null && !v.isBlank()) parts.add(v);
    }

    /** Flatten Frappe's HTML {@code address_display} (&lt;br&gt; lines) into a comma-separated string. */
    private static String stripHtml(String html) {
        if (html == null) return null;
        String s = html.replaceAll("(?i)<br\\s*/?>", ", ").replaceAll("<[^>]+>", " ")
                .replaceAll("\\s+", " ").trim();
        s = s.replaceAll("(,\\s*)+", ", ").replaceAll("^,\\s*|,\\s*$", "").trim();
        return s.isBlank() ? null : s;
    }

    private static String firstNonBlank(String... vals) {
        for (String v : vals) if (v != null && !v.isBlank()) return v;
        return null;
    }

    private static String orEmpty(String s) {
        return s != null ? s : "";
    }
}
