@startuml
!pragma layout smetana
left to right direction
skinparam actorStyle awesome
skinparam backgroundColor white
skinparam usecase {
  BackgroundColor #EEF4FF
  BorderColor #0052A3
  ArrowColor #333333
}

actor "Chauffeur" as CH

rectangle "Exécution et confirmation de livraison" {

  usecase "S'authentifier sur\nl'application mobile" as AUTH

  usecase "Consulter ses tournées\nvalidées de la semaine" as UC1
  usecase "Démarrer la tournée" as UC2
  usecase "Démarrer le transit\nvers un arrêt" as UC3
  usecase "Confirmer la livraison\navec capture POD" as UC4
  usecase "Confirmer une\nlivraison partielle" as EX1
  usecase "Déclarer un arrêt échoué\n(motif + commentaire)" as EX2
  usecase "Consulter ses statistiques\nde performance" as UC5
}

CH --> UC1
CH --> UC2
CH --> UC3
CH --> UC4
CH --> UC5

' <<include>>
UC1 ..> AUTH : <<include>>
UC2 ..> AUTH : <<include>>
UC3 ..> AUTH : <<include>>
UC4 ..> AUTH : <<include>>
UC5 ..> AUTH : <<include>>

' <<extend>>
EX1 ..> UC4 : <<extend>>\n{si livraison\nincomplète}
EX2 ..> UC4 : <<extend>>\n{si livraison impossible —\nsélection motif}

' forcer positions
UC4 -[hidden]right- EX1
UC4 -[hidden]right- EX2

@enduml
